name: cats
homepage: https://github.com/gql-dart/gql/cats
description: A starting point for Dart libraries or applications.
environment: 
  sdk: '>=2.7.2 <3.0.0'
dependencies: 
  test: ^1.6.0
dev_dependencies: 
  pedantic: ^1.7.0
  yaml: ^2.1.16
